[32.911300659] 2018-07-14 21:02:41,996 - INFO - launcher: Starting sanity checks
[32.911300659] 2018-07-14 21:02:41,996 - INFO - launcher: Checking for Python 3.5+
[32.911300659] 2018-07-14 21:02:41,996 - INFO - launcher: Checking console encoding
[33.908843994] 2018-07-14 21:02:41,997 - INFO - launcher: Setting console encoding to UTF-8
[33.908843994] 2018-07-14 21:02:41,997 - INFO - launcher: Ensuring we're in the right environment
[34.905910492] 2018-07-14 21:02:41,998 - INFO - launcher: Adding local bins/ folder to path
[34.905910492] 2018-07-14 21:02:41,998 - INFO - launcher: Required checks passed.
[36.900043488] 2018-07-14 21:02:42,000 - INFO - launcher: Optional checks passed.
[36.900043488] 2018-07-14 21:02:42,000 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.9414813518524170] 2018-07-14 21:02:42,905 - WARNING - musicbot.config | In config.py::MainThread(15948), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.9424779415130615] 2018-07-14 21:02:42,906 - INFO - musicbot.config | In config.py::MainThread(15948), line 123 in run_checks: Using i18n: config/i18n/en.json
[0.9444723129272461] 2018-07-14 21:02:42,908 - DEBUG - musicbot.json | In json.py::MainThread(15948), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.3985848426818848] 2018-07-14 21:02:43,362 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 227 in _setup_logging: Set logging level to INFO
[1.3985848426818848] 2018-07-14 21:02:43,362 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 84 in __init__: Starting MusicBot 1.9.7
[1.3995819091796875] 2018-07-14 21:02:43,363 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 90 in __init__: Loaded autoplaylist with 2531 entries
[1.5771071910858154] 2018-07-14 21:02:43,541 - DEBUG - musicbot.spotify | In spotify.py::MainThread(15948), line 70 in get_token: Created a new access token: {'access_token': 'BQCOLiudgnJsWG0444_NqWesX4P2At1PJD2dO0YiSTxiv09-AoqI-6KqDejopA9UjKz3ez3mSdmZTaY30h0', 'expires_in': 3600, 'expires_at': 1531602163, 'scope': '', 'token_type': 'Bearer'}
[1.5771071910858154] 2018-07-14 21:02:43,541 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 115 in __init__: Authenticated with Spotify successfully using client ID and secret.
[4.3083238601684570] 2018-07-14 21:02:46,272 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 1074 in on_ready: Connection established, ready to go.
[4.3083238601684570] 2018-07-14 21:02:46,272 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 339 in _cache_app_info: Caching app info
[6.8817620277404785] 2018-07-14 21:02:48,845 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2734 in on_message: 101405806343254016/Ethan#2269: -play
[6.8827600479125977] 2018-07-14 21:02:48,846 - ERROR - musicbot.bot | In bot.py::MainThread(15948), line 2863 in on_message: Error in play: CommandError: The bot is not in a voice channel.  Use -play to play it to your voice channel.
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 2762, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %splay to play it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use -play to play it to your voice channel.
[17.0405111312866211] 2018-07-14 21:02:59,004 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 889 in _scheck_ensure_env: Ensuring data folders exist
[17.0435035228729248] 2018-07-14 21:02:59,007 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 905 in _scheck_server_permissions: Checking server permissions
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 913 in _scheck_configs: Validating config
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.config | In config.py::MainThread(15948), line 212 in async_validate: Validating options...
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.config | In config.py::MainThread(15948), line 226 in async_validate: Acquired owner id via API
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 916 in _scheck_configs: Validating permissions config
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.permissions | In permissions.py::MainThread(15948), line 64 in async_validate: Validating permissions...
[17.0445003509521484] 2018-07-14 21:02:59,008 - DEBUG - musicbot.permissions | In permissions.py::MainThread(15948), line 68 in async_validate: Fixing automatic owner group
[17.0445003509521484] 2018-07-14 21:02:59,008 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1091 in on_ready: Connected: 467767083363467314/Sonubot#1812
[17.0454969406127930] 2018-07-14 21:02:59,009 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1099 in on_ready: Owner:     101405806343254016/Ethan#2269

[17.0454969406127930] 2018-07-14 21:02:59,009 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1102 in on_ready: Server List:
[17.0464947223663330] 2018-07-14 21:02:59,010 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1105 in on_ready:  - twitch.tv/sonocs
[17.0464947223663330] 2018-07-14 21:02:59,010 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1151 in on_ready: Not bound to any text channels
[17.0464947223663330] 2018-07-14 21:02:59,010 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1177 in on_ready: Not autojoining any voice channels
[17.0474915504455566] 2018-07-14 21:02:59,011 - WARNING - musicbot.bot | In bot.py::MainThread(15948), line 1217 in on_ready: Your config file is missing some options. If you have recently updated, check the example_options.ini file to see if there are new options available to you. The options missing are: {'autosummon'}
[30.1410236358642578] 2018-07-14 21:03:12,105 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2734 in on_message: 101405806343254016/Ethan#2269: -play Drake - nonstop (audio)
[30.1420383453369141] 2018-07-14 21:03:12,106 - ERROR - musicbot.bot | In bot.py::MainThread(15948), line 2863 in on_message: Error in play: CommandError: The bot is not in a voice channel.  Use -play to play it to your voice channel.
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 2762, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %splay to play it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use -play to play it to your voice channel.
[32.9574770927429199] 2018-07-14 21:03:14,921 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2734 in on_message: 101405806343254016/Ethan#2269: -play
[32.9604687690734863] 2018-07-14 21:03:14,924 - ERROR - musicbot.bot | In bot.py::MainThread(15948), line 2863 in on_message: Error in play: CommandError: The bot is not in a voice channel.  Use -play to play it to your voice channel.
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 2762, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %splay to play it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use -play to play it to your voice channel.
[35.8822650909423828] 2018-07-14 21:03:17,846 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2734 in on_message: 101405806343254016/Ethan#2269: -join
[35.8822650909423828] 2018-07-14 21:03:17,846 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2019 in cmd_join: Joining twitch.tv/sonocs/Music
[35.8832342624664307] 2018-07-14 21:03:17,847 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 452 in get_voice_client: Connection attempt 1 to Music
[35.8832342624664307] 2018-07-14 21:03:17,847 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 391 in join_voice_channel: (join_voice_channel) creating futures
[35.8832342624664307] 2018-07-14 21:03:17,847 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 397 in join_voice_channel: (join_voice_channel) setting voice state
[35.8842349052429199] 2018-07-14 21:03:17,848 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 400 in join_voice_channel: (join_voice_channel) waiting for session id
[36.0158786773681641] 2018-07-14 21:03:17,979 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 2938 in on_voice_state_update: Voice state update for 467767083363467314/Sonubot#1812 on twitch.tv/sonocs/Music -> [JOIN, CONNECT]
[36.0169017314910889] 2018-07-14 21:03:17,980 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2949 in on_voice_state_update: 467767083363467314/Sonubot#1812 has joined twitch.tv/sonocs/Music
[36.0178740024566650] 2018-07-14 21:03:17,981 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 404 in join_voice_channel: (join_voice_channel) waiting for voice data
[36.1056680679321289] 2018-07-14 21:03:18,069 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 418 in join_voice_channel: (join_voice_channel) connecting...
[36.3670372962951660] 2018-07-14 21:03:18,331 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 430 in join_voice_channel: (join_voice_channel) connection successful
[36.3670372962951660] 2018-07-14 21:03:18,331 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 478 in get_voice_client: Connected in 0.5s
[36.3679668903350830] 2018-07-14 21:03:18,332 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 479 in get_voice_client: Connected to twitch.tv/sonocs/Music
[36.3689398765563965] 2018-07-14 21:03:18,333 - VOICEDEBUG - musicbot.player | In player.py::MainThread(15948), line 373 in websocket_check: Starting websocket check loop for twitch.tv/sonocs
[52.7077584266662598] 2018-07-14 21:03:34,671 - ERROR - musicbot.bot | In bot.py::MainThread(15948), line 2886 in on_message: Exception in on_message
Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 937, in safe_send_message
    msg = await self.send_message(dest, embed=content)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 2859, in on_message
    also_delete=message if self.config.delete_invoking else None
  File "C:\Users\Ethan\Desktop\MusicBot\musicbot\bot.py", line 948, in safe_send_message
    if len(content) > DISCORD_MSG_CHAR_LIMIT:
TypeError: object of type 'Embed' has no len()
[62.1478707790374756] 2018-07-14 21:03:44,111 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2734 in on_message: 101405806343254016/Ethan#2269: -restart
[62.5654387474060059] 2018-07-14 21:03:44,529 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(15948), line 2938 in on_voice_state_update: Voice state update for 467767083363467314/Sonubot#1812 on twitch.tv/sonocs/Music -> [DISCONNECT]
[62.580373764] launcher-INFO: Restarting in 2 seconds...
[64.5832240581512451] 2018-07-14 21:03:46,547 - WARNING - musicbot.config | In config.py::MainThread(15948), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[64.5842208862304688] 2018-07-14 21:03:46,548 - INFO - musicbot.config | In config.py::MainThread(15948), line 123 in run_checks: Using i18n: config/i18n/en.json
[64.5872123241424561] 2018-07-14 21:03:46,551 - DEBUG - musicbot.json | In json.py::MainThread(15948), line 8 in __init__: Init JSON obj with config/i18n/en.json
[64.6001775264739990] 2018-07-14 21:03:46,564 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 192 in _setup_logging: Skipping logger setup, already set up
[64.6001775264739990] 2018-07-14 21:03:46,564 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 84 in __init__: Starting MusicBot 1.9.7
[64.6011750698089600] 2018-07-14 21:03:46,565 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 90 in __init__: Loaded autoplaylist with 2531 entries
[64.7321114540100098] 2018-07-14 21:03:46,696 - DEBUG - musicbot.spotify | In spotify.py::MainThread(15948), line 70 in get_token: Created a new access token: {'access_token': 'BQDmfYQ0etqh1ZsU6t4SbTHAXJRQSpcIrVXUQGp8DPg6erHJ3qFWmr0IiCGHdmcMdZUtw1qrnb_IUkCK1QM', 'expires_in': 3600, 'expires_at': 1531602226, 'scope': '', 'token_type': 'Bearer'}
[64.7321114540100098] 2018-07-14 21:03:46,696 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 115 in __init__: Authenticated with Spotify successfully using client ID and secret.
[67.4048867225646973] 2018-07-14 21:03:49,368 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 1074 in on_ready: Connection established, ready to go.
[67.4048867225646973] 2018-07-14 21:03:49,368 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 339 in _cache_app_info: Caching app info
[67.5452497005462646] 2018-07-14 21:03:49,509 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 889 in _scheck_ensure_env: Ensuring data folders exist
[67.5492358207702637] 2018-07-14 21:03:49,513 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 905 in _scheck_server_permissions: Checking server permissions
[67.5492358207702637] 2018-07-14 21:03:49,513 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[67.5492358207702637] 2018-07-14 21:03:49,513 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 913 in _scheck_configs: Validating config
[67.5492358207702637] 2018-07-14 21:03:49,513 - DEBUG - musicbot.config | In config.py::MainThread(15948), line 212 in async_validate: Validating options...
[67.5502040386199951] 2018-07-14 21:03:49,514 - DEBUG - musicbot.config | In config.py::MainThread(15948), line 226 in async_validate: Acquired owner id via API
[67.5502040386199951] 2018-07-14 21:03:49,514 - DEBUG - musicbot.bot | In bot.py::MainThread(15948), line 916 in _scheck_configs: Validating permissions config
[67.5502040386199951] 2018-07-14 21:03:49,514 - DEBUG - musicbot.permissions | In permissions.py::MainThread(15948), line 64 in async_validate: Validating permissions...
[67.5502040386199951] 2018-07-14 21:03:49,514 - DEBUG - musicbot.permissions | In permissions.py::MainThread(15948), line 68 in async_validate: Fixing automatic owner group
[67.5502040386199951] 2018-07-14 21:03:49,514 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1091 in on_ready: Connected: 467767083363467314/Sonubot#1812
[67.5512022972106934] 2018-07-14 21:03:49,515 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1099 in on_ready: Owner:     101405806343254016/Ethan#2269

[67.5531947612762451] 2018-07-14 21:03:49,517 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1102 in on_ready: Server List:
[67.5541923046112061] 2018-07-14 21:03:49,518 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1105 in on_ready:  - twitch.tv/sonocs
[67.5551922321319580] 2018-07-14 21:03:49,519 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1151 in on_ready: Not bound to any text channels
[67.5571866035461426] 2018-07-14 21:03:49,521 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 1177 in on_ready: Not autojoining any voice channels
[67.5591790676116943] 2018-07-14 21:03:49,523 - WARNING - musicbot.bot | In bot.py::MainThread(15948), line 1217 in on_ready: Your config file is missing some options. If you have recently updated, check the example_options.ini file to see if there are new options available to you. The options missing are: {'autosummon'}
[87.2210485935211182] 2018-07-14 21:04:09,185 - INFO - musicbot.bot | In bot.py::MainThread(15948), line 2734 in on_message: 101405806343254016/Ethan#2269: -join
